theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: content
  posts:
    index:
      layout: grid
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"